# Generated by Django 5.0.1 on 2024-01-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profiledetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
